### ISSUE TITLE
VNV - Reflection/Appendix

### ISSUE THREAD

**Issue by jsontran** [SumanyaG/Alkalytics#132]

**Comment by katemin991** [comment]
the questions
1. What knowledge and skills will the team collectively need to acquire to successfully complete the verification and validation of your project? Examples of possible knowledge and skills include dynamic testing knowledge, static testing knowledge, specific tool usage, Valgrind etc.  You should look to identify at least one item for each team member.
2. For each of the knowledge areas and skills identified in the previous question, what are at least two approaches to acquiring the knowledge or mastering the skill?  Of the identified approaches, which will each team member pursue, and why did they make this choice?

**Comment by JenniferYe25** [comment]
1. While doing the system tests, it was required that we know how the system works even though we are still in the early stages of documentation. By piecing together all the written documents so far along with the conversations we had a team can create a more clear picture of what exactly what are the success criteria for each function. In addition to being able to build on top of what was already written, knowing the difference between the different types of testings, how to use them, when each should be used and when to define a different type of test. Another thing that was very quickly noted is that even though there are many requirements, many can be grouped with one system test. Knowing when to group them was critical for this milestone. 

4. One way to approach to master the skill of creating and classifying tests is through practice and having a good understanding of them. As such, reading up on the different types of testing along with the pros and cons of each will help give the background needed to make a good decision.  Another way is to write out different types of tests for each requirement and narrow down the best type of test to satisfy the requirement. We went with the first option as it is not only more efficient with the time given but also it allows us to think critically and carefully about what needs to be done and why instead of write out a bunch of tests and picking out which one would be the best. Although that is a good exercise, it is not the best solution to learning and mastering testing.

**Comment by jsontran** [comment]
1) I will focus on refining my dynamic testing skills because my experience through previous co-ops has shown that dynamic testing is vital for identifying runtime issues that static testing might miss. This approach allows us to evaluate the application's behaviour in real-time, ensuring that performance, and user interactions are optimized. 

2) To acquire my dynamic testing skills, I will focus on two main approaches, mentoring and online resources. By helping a less experienced teammate, I will reaffirm my understanding of dynamic testing concepts and techniques through teaching and collaboration. Moreover, I will use online resources such as tutorials and documentation to explore advanced topics and stay updated on best practices.

**Comment by SumanyaG** [comment]
1. Through my past co-ops, I have had a chance to use static and dynamic testing techniques but I have never had the chance to use automated testing and continuous integration. Since we plan on using linters for this project, I would like to use this opportunity to build proficiency in setting up and running linters to improve testing efficiency by diagnosing and automatically resolving technical issues.
2. One approach to do this is by setting up a linter in a development environment and applying it to existing codebases. This hands-on approach will help me become familiar with the specific rules, configurations, and output of the linter. Another approach can be to enrol in an online course that focuses on setting up and using popular linters, covering topics like configuring rules, enforcing best practices, and automating linting as part of CI/CD pipelines. Of these, two, I would choose the former approach as I believe this approach builds familiarity with real-world usage and configuration of linters, making it easier to customize and apply them effectively.
