### ISSUE TITLE
SRS - Reflection

### ISSUE THREAD

**Issue by SumanyaG** [SumanyaG/Alkalytics#56]
The information in this section will be used to evaluate the team members on the graduate attribute of Lifelong Learning. Please answer the following questions:

1. What knowledge and skills will the team collectively need to acquire to successfully complete this capstone project? Examples of possible knowledge to acquire include domain specific knowledge from the domain of your application, or software engineering knowledge, mechatronics knowledge or computer science knowledge. Skills may be related to technology, or writing, or presentation, or team management, etc. You should look to identify at least one item for each team member.

2.  For each of the knowledge areas and skills identified in the previous question, what are at least two approaches to acquiring the knowledge or mastering the skill? Of the identified approaches, which will each team member pursue, and why did they make this choice?

**Comment by SumanyaG** [comment]
1. Using version control conventions and such for a large-scale project. In the past, my use of git has been limited to just storing code in a centralized repository that my team members could access. We did not do any proper documentation or reviews. This is the first project where our team has come up with a merging strategy, naming conventions and more to keep the git history clean and to ensure conformity and proper documentation. In terms of technology, I have never worked with NoSQL databases before so I am looking forward to exploring that!

2. The two approaches to mastering git and NoSQL databases would be following a tutorial to learn how git works and basic commands; and, just practicing it for all deliverables and learning along the way. I will be leveraging my existing knowledge of git commands and workflows and use it to learn how it can be adapted to large-scale, long-term projects that are maintainable and scalable. As for the NoSQL database, I would choose the former strategy and follow a guided tutorial first to familiarize myself with the topic so I can actually contribute to the project.

**Comment by JenniferYe25** [comment]
1. Although I have good skills in writing and team management, the one item that I will need to acquire in this capstone is my back-end knowledge. I know how back-end applications works with aspects like APIs and databases as a general concept, but I have no real experience with implementation. With this capstone project being an end-to-end project, with a focus on back end, I believe it will be critical for me to grain that knowledge to be an impactful team member to the project. More specifically, I will need to acquire more advanced knowledge of databases and API creation. My strength is in mobile and web development, but since that portion of the project is in the later half of the project, I do not want to wait for then to be impactful. I would like to learn and practice the knowledge throughout the term. 

2. One approach I will use to learn more about API and database creation is to follow tutorial crash courses. With this method, I can have a clearer fundamental understanding on the concepts. This might include parts like how they operate, simple manipulation and customization. Another approach which can also serve as a follow up approach will be to use them in practice and to learn as I go. This can be in the form of a quick side project. I will be pursuing both as I deem it necessary to be able to succeed in gaining the knowledge in a valuable way. I think learning all the content/knowledge of the back-end from tutorials and cash courses might even be all I need to gain the knowledge and contribute to the project on that front. However, with my learning style, I would do better if I also applied the things I learned. This can be done straight from the capstone project, or even having a small side project to just apply what I learned before going into the project is another possibility. In conclusion, I will be using the first method to gain the knowledge I need but will also do the second method due to my learning style.

**Comment by jsontran** [comment]
To successfully complete our project, I will need to learn more about backend and data migration. As I have more professional experience with the frontend or how to connect the front end to the backend, I will now need to learn the final step of creating the backend itself. This includes how to code with Python and how to create algorithms myself.

I will utilize two approach on my learning experience, which is to explore resources online and jump straight into the deep end. This will apply what I have learned online in a real application which, in my experience, allows me to connect the dots a lot faster. Ultimately, jumping into the deep end will help progress the project along and create an iterative learning style.

**Comment by katemin991** [comment]
we have additional reflection questions!!

1. What went well while writing this deliverable? 
2. What pain points did you experience during this deliverable, and how did you resolve them?
3. How many of your requirements were inspired by speaking to your client(s) or their proxies (e.g. your peers, stakeholders, potential users)?
4. Which of the courses you have taken, or are currently taking, will help your team to be successful with your capstone project?

the ones we have answers for are questions 5 and 6, respectively

**Comment by SumanyaG** [comment]
> we have additional reflection questions!!
> 
> 1. What went well while writing this deliverable?
> 2. What pain points did you experience during this deliverable, and how did you resolve them?
> 3. How many of your requirements were inspired by speaking to your client(s) or their proxies (e.g. your peers, stakeholders, potential users)?
> 4. Which of the courses you have taken, or are currently taking, will help your team to be successful with your capstone project?
> 
> the ones we have answers for are questions 5 and 6, respectively

Oh LOL. I can write up responses for these and we can answer these as a group?

**Comment by SumanyaG** [comment]
1. Writing this deliverable gave us greater clarity regarding the project and made us think of questions we hadn't considered before such as what our data migration plan would look like, if we need RBAC (Role Based Access Control) and what each role and security level should include and more.

2. The major pain point for this deliverable was the length and the amount of content that had to be condensed into a single document in such a short span of time. With deadline for other courses, coordinating with supervisors and giving them enough time to review our SRS for feedback - most of the steps felt rushed. Since the Volere template is so detailed, we also ran into multiple issues where we either did not know what a section or sub-section was asking for or figuring out what to write for a non-relevant section that is included in the rubric.

3. Most of our FRs were inspired by our client, primarily our supervisors. Since they do not have a concrete plan for how they want this project implemented and instead have an abstract idea of what they would want to see in the product, it gave us a lot more room to be creative and consider multiple scenarios for our requirements, ultimately choosing the ones that suit our project the best. Most of the NFRs had to be brainstormed by our team and then validated by the stakeholders since they hadn't given much thought to these aspects of the product.

4. 3RA3 or Software Engineering Requirements was very helpful in writing up the SRS because we weren't completely clueless and did not have to spend a lot of time researching what an SRS is or what requirements are. This meant we could dive straight into work. Another course that has been helpful is 3DB3 or Databases mostly because after taking that course, we've had experience dealing with relational databases and were able to determine very early on how a relational database would not be the most suitable for our project and thus, pivot towards NoSQL databases. 

@katemin991 @JenniferYe25 @jsontran let me know if you'd like to add anything else (ore remove, for that matter) to these answers! I was considering adding 3A04 for Q4 but I'm not entirely sure.

**Comment by katemin991** [comment]
we could add a bit extra to 1 and 2:
1. Additionally, we had already acquired significant knowledge about our supervisors' needs/expectations for the project before we began the writing process, which gave us a clearer guide on modelling our requirements and allowed us to start earlier rather than later. As a result, we were able to develop an initial draft, which they reviewed and provided feedback on, enabling us to refine our document in an iterative manner.
2. However, we were able to address our questions and concerns through a meeting that we had scheduled with our TA, on top of the informal review session. This helped us gain a better understanding of the expectations for each section we faced difficulties with.
