### ISSUE TITLE
SRS - 12 Performance Requirements

### ISSUE THREAD

**Issue by katemin991** [SumanyaG/Alkalytics#72]

**Comment by jsontran** [comment]
As of now, I dont see a rationale or fit criterion for the PR. I know that we can skip fit criterions if its clear in the requirements, but not sure if we can skip rationale. If not, then we should add them.

PR-2) What if they have bad internet connection? Maybe state with good internet/stable connection
PR-3) Same thing with computer speeds, what if their computers are slow LOL. maybe mention an average P4-5) is there a reason why the requirement code is like that <-? Also what if its super big database and will take a little more time to generate a visual (im assuming its like plotting every single dot), maybe say average? or something relative to the data size
PR-11) why only three? like three accounts in total or three users using the same account? and if its three users on same account, how will we approach like two people editing something at the exact same time, i think it will break something due to race conditions. I think 1 user per account make more sense
PR-12) for fit criterion, you say it will satisy the requirement above, im assuming now we dont need it if its clear

**Comment by katemin991** [comment]
> As of now, I dont see a rationale or fit criterion for the PR. I know that we can skip fit criterions if its clear in the requirements, but not sure if we can skip rationale. If not, then we should add them.
> PR-2) What if they have bad internet connection? Maybe state with good internet/stable connection 
> PR-3) Same thing with computer speeds, what if their computers are slow LOL. maybe mention an average 
> P4-5) is there a reason why the requirement code is like that <-? Also what if its super big database and will take a little more time to generate a visual (im assuming its like plotting every single dot), maybe say average? or something relative to the data size 
> PR-11) why only three? like three accounts in total or three users using the same account? and if its three users on same account, how will we approach like two people editing something at the exact same time, i think it will break something due to race conditions. I think 1 user per account make more sense 
PR-12) for fit criterion, you say it will satisy the requirement above, im assuming now we dont need it if its clear

the rationale and fit criterion at the bottom applies to all of the reqs in the subsection bc i thought it would be redundant to repeat for each one. i'll add rationale to each req but not sure how to structure the fit criterion - typically if the requirement already includes some sort of quantification, it doesn't need fit criterion (according to volere template), so i don't want to repeat that it should satisfy the req above for each req, but we can discuss that in the gc
PR-2, 3: makes sense, will modify
PR-4, 5: i just made it up LOL i will modify that
PR-11: in our meeting with bassel on the 1st(?) he said there'd be up to 2-3 users so it just means there'd be up to 3 users accessing the application. i didn't take accounts into consideration at the time, but yeah it would be 1 user per account. i'm not sure how to modify the requirement to make that distinction clear. i don't think mentioning account-user info belongs in this subsection though bc it's just about the capacity the app should be able to handle and not specifically how each user should be accessing it if that makes sense?
