### ISSUE TITLE
SRS - 13 Operational and Environmental Requirements

### ISSUE THREAD

**Issue by katemin991** [SumanyaG/Alkalytics#73]

**Comment by jsontran** [comment]
OER-2) I think it should work on all OS, since they all using a web browser to access it
OER-3) when coding on safari theres like key differences while coding frontend stuff, so maybe just say chormium based browsers (all browsers that uses chrome as a library essientially) instead. Cause I think we should focus on chrome (and related browsers) more than a specfic case for safari when coding

LGTM

**Comment by katemin991** [comment]
> OER-2) I think it should work on all OS, since they all using a web browser to access it 
> OER-3) when coding on safari theres like key differences while coding frontend stuff, so maybe just say chormium based browsers (all browsers that uses chrome as a library essientially) instead. Cause I think we should focus on chrome (and related browsers) more than a specfic case for safari when coding

for OER-2, i referred to section 3.2 in which we specify the implementation environment as Windows. i think we should re-discuss this req to be consistent so i won't modify it yet
OER-3 shall be changed
