### ISSUE TITLE
SRS - 14 Maintainability and Support Requirements

### ISSUE THREAD

**Issue by jsontran** [SumanyaG/Alkalytics#75]

**Comment by katemin991** [comment]
MSR-2) i think we discussed this in the meeting, but would there be another dev team after us? if it's unknown (or if the prof clarifies there won't be another dev team) then i'm not sure if we should be pointing out the possibility of transferring knowledge to a new dev team in the requirements.
MSR-4 fit criterion) should complete -> should be able to complete?
otherwise lgtm

**Comment by jsontran** [comment]
Yea, I think he said that he wants to personally be the one to maintain the project after us and asked us to give him some documentation for that. Thats why we were talking about developer documentation last time

**Comment by katemin991** [comment]
ah ok i see, then should we instead say that it would be maintained by one of the end-users? or by developers who are not the original developers. something along those lines.
to me, "new developers" sounds like there'd be a dedicated new team of devs that would be maintaining the app
