### ISSUE TITLE
SRS - 15 Security Requirements

### ISSUE THREAD

**Issue by jsontran** [SumanyaG/Alkalytics#78]

**Comment by katemin991** [comment]
MSR-2) i think we discussed this in the meeting, but would there be another dev team after us? if it's unknown (or if the prof clarifies there won't be another dev team) then i'm not sure if we should be pointing out the possibility of transferring knowledge to a new dev team in the requirements.
MSR-4 fit criterion) should complete -> should be able to complete?
otherwise lgtm
