### ISSUE TITLE
SRS - 1 Purpose of the Project

### ISSUE THREAD

**Issue by JenniferYe25** [SumanyaG/Alkalytics#81]

**Comment by jsontran** [comment]
1) instead of saying the platform to refer to the product, say application, as per the discussion in the gc
1.1) per the prof's email, instead of balancing ocean's pH, it should be decrease it.
1.2) "data points from anywhere", sounds like location more than data point, remove from anywhere
1.2) data sets - > datasets

**Comment by katemin991** [comment]
1.1) "the product serves a niche solution..": the wording here doesn't flow well. also, what is "the product" referring to? if it's our application, it doesn't really make sense because it's not doing anything directly to decrease the ocean's pH. 
what's the problem that the solution is trying to solve? it would be good to mention how the experiment study is meant to tackle climate change (decreasing pH -> more co2 absorption -> less co2 in the atmosphere -> reduce global temperatures)
the following sentence "as earth's temperature rises..." doesn't flow and it doesn't really explain anything (what's the significance of the pH balance being affected?)

1.2) "centralize" -> "centralized"?
